displayName=World Map Player Indicator
author=jpee
description=Places an arrow indicator for the characters facing direction on the world map.
tags=map,player,character,arrow,indicator,world,direction
plugins=com.MapPlayerIndicator.PlayerIndicatorPlugin