displayName=Player Arrow Indicator
author=jpee
description=Replaces the map indicators with an arrow relating to the direction that the character is facing.
tags=map,player,character,arrow,indicator,world,direction
plugins=com.MapPlayerIndicator.PlayerIndicatorPlugin